##
## Makefile for  in /blinux_home/bazin_q/rendu/PSU_2015_my_select
##
## Made by Quentin Bazin
## Login   <bazin_q@epitech.net>
##
## Started on  Tue Dec 01 15:46:23 2015 Quentin Bazin
## Last update Fri Apr 29 15:40:21 2016 Benjamin Audet
##

NAME		= mysh

INC_DIRS	= include

SOURCES		= autocomplet.c \
						list_manage.c \
						list_manipulation.c \
						error.c

SOURCES2	=	autocomplet2.c \
						list_manage2.c \
						list_manipulation2.c \
						error.c

MY_LIBS		= my_printf my

include Makefile.libmy
include Makefile.common
